<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Gabrielp" ignored="0" name="Command line test" tests="13" failures="8" timestamp="20 avr. 2018 07:03:47 GMT" time="0.251" errors="0">
  <testcase name="testPosition" time="0.004" classname="dao.EchecsDaoNGTest">
    <failure type="java.lang.AssertionError" message="The test case is a prototype.">
      <![CDATA[java.lang.AssertionError: The test case is a prototype.
at dao.EchecsDaoNGTest.testPosition(EchecsDaoNGTest.java:66)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testPosition -->
  <testcase name="testReadEchec" time="0.006" classname="dao.EchecsDaoNGTest">
    <failure type="java.lang.AssertionError" message="The test case is a prototype.">
      <![CDATA[java.lang.AssertionError: The test case is a prototype.
at dao.EchecsDaoNGTest.testReadEchec(EchecsDaoNGTest.java:52)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testReadEchec -->
  <testcase name="testWriteEchec" time="0.001" classname="dao.EchecsDaoNGTest">
    <failure type="java.lang.AssertionError" message="The test case is a prototype.">
      <![CDATA[java.lang.AssertionError: The test case is a prototype.
at dao.EchecsDaoNGTest.testWriteEchec(EchecsDaoNGTest.java:78)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testWriteEchec -->
  <testcase name="testMain" time="0.132" classname="echecs.MainNGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at vue.FrmMain.<init>(FrmMain.java:11)
at echecs.Main.main(Main.java:9)
at echecs.MainNGTest.testMain(MainNGTest.java:47)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testMain -->
  <testcase name="testCompareTo" time="0.0" classname="elo.JoueurNGTest"/>
  <testcase name="testGetNom" time="0.0" classname="elo.JoueurNGTest"/>
  <testcase name="testGetPoints" time="0.0" classname="elo.JoueurNGTest"/>
  <testcase name="testToString" time="0.001" classname="elo.JoueurNGTest"/>
  <testcase name="testToText" time="0.0" classname="elo.JoueurNGTest"/>
  <testcase name="testFermer" time="0.009" classname="vue.FrmMainNGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at vue.FrmMain.<init>(FrmMain.java:11)
at vue.FrmMainNGTest.testFermer(FrmMainNGTest.java:47)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testFermer -->
  <testcase name="testRetourne" time="0.009" classname="vue.FrmMainNGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at vue.FrmMain.<init>(FrmMain.java:11)
at vue.FrmMainNGTest.testRetourne(FrmMainNGTest.java:60)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testRetourne -->
  <testcase name="testGetInstance" time="0.032" classname="vue.FrmNouveauNGTest">
    <failure type="java.lang.AssertionError" message="expected [null] but found [vue.FrmNouveau[frame0,0,0,337x297,invalid,hidden,layout=javax.swing.GroupLayout,title=Saisie d&amp;apos;un nouveau joueur,resizable,normal]]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [vue.FrmNouveau[frame0,0,0,337x297,invalid,hidden,layout=javax.swing.GroupLayout,title=Saisie d'un nouveau joueur,resizable,normal]]
at vue.FrmNouveauNGTest.testGetInstance(FrmNouveauNGTest.java:49)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- testGetInstance -->
  <testcase name="testValide" time="0.018" classname="vue.FrmNouveauNGTest">
    <failure type="java.lang.AssertionError" message="The test case is a prototype.">
      <![CDATA[java.lang.AssertionError: The test case is a prototype.
at vue.FrmNouveauNGTest.testValide(FrmNouveauNGTest.java:65)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testValide -->
</testsuite> <!-- Command line test -->
